export const USER_ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
} as const;

export const SHIFT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const SCHEDULE_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const TIME_OFF_TYPES = {
  ANNUAL_LEAVE: 'ANNUAL_LEAVE',
  SICK_LEAVE: 'SICK_LEAVE',
  UNPAID_LEAVE: 'UNPAID_LEAVE',
  PUBLIC_HOLIDAY: 'PUBLIC_HOLIDAY',
  OTHER: 'OTHER',
} as const;

export const CONFLICT_SEVERITY = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL',
} as const;

export const RULE_TYPES = {
  MIN_REST_BETWEEN_SHIFTS: 'MIN_REST_BETWEEN_SHIFTS',
  MAX_CONSECUTIVE_DAYS: 'MAX_CONSECUTIVE_DAYS',
  MAX_WEEKLY_HOURS: 'MAX_WEEKLY_HOURS',
  MIN_STAFF_PER_SHIFT: 'MIN_STAFF_PER_SHIFT',
  MAX_STAFF_PER_SHIFT: 'MAX_STAFF_PER_SHIFT',
  REQUIRED_SKILLS: 'REQUIRED_SKILLS',
  WEEKEND_RULES: 'WEEKEND_RULES',
} as const;
